### ISSUE TITLE
Does the demo code require Spotify Plugin?

### ISSUE THREAD

**Issue by marctwo** [piotrraczynski/squeezenode#7]
I can't seem to get the Demo code to work. It runs, and I get the command prompt but none of the commands work, not even 'help'. I don't get any errors. Could this be due to the lack of Spotify plugin on LMS?

**Comment by piotrraczynski** [comment]
Yes it needs Triode's Spotify plugin (not the default one) and also Spotify Premium account (with proper configuration under Squeezebox web gui).

**Comment by marctwo** [comment]
Thanks for the reply. So you are saying that the code will not work at all (not even 'help' to get a list of commands) unless I have the Spotify plugin installed?

**Comment by piotrraczynski** [comment]
Yes, the way this demo application at this point won't bring up the CLI
until it gets connected to the server with Spotify plugin installed and
configured.

--
Pozdrawiam,
Piotr Raczyński

2015-08-12 12:54 GMT-07:00 marctwo <notifications@github.com>:

**Comment by marctwo** [comment]
OK, thank you for the clarification.
